spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:mysql://localhost:3306/seolstudy
    username: root
    password: 0907

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  file:
    upload-dir: /data/uploads
