spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:mysql://localhost:3306/seolstudy
    username: nat
    password: 1q2w3e4r!@

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

  file:
    upload-dir: D:\2_Coding\3_Project\seolstudy\files
