spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:mysql://localhost:3306/seolstudy
    username: root
    password: 0907

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  
  file:
    upload-dir: D:\2_Coding\3_Project\seolstudy\files
